# Generated by Django 5.0.1 on 2024-02-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
    ]
