# Generated by Django 5.0.1 on 2024-02-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
